### ISSUE TITLE
支持JTT 809 2019版本

### ISSUE THREAD

**Issue by liaoyongxiong** [SmallChi/JT809#1]
809 2019版本见附件。
后续的过检，陆陆续续要求支持808/809 2019版本
[JTT 809-2019.PDF](https://github.com/SmallChi/JT809/files/4007195/JTT.809-2019.PDF)

**Comment by wangyoulin006** [comment]
现在 支持2019版本 吧。谢谢

**Comment by SmallChi** [comment]
嗯，在开发中...最快也要中旬这样子吧

**Comment by KIngCrzy** [comment]
你好 能问问怎么用吗  没学过c#  但是现在需要自己组向上级平台请求的报文 就是主链路登录请求之类的

**Comment by SmallChi** [comment]
大兄弟，这个问题比较严重，没有学过c#，那你只能慢慢来了   ╮(╯▽╰)╭

**Comment by KIngCrzy** [comment]
> 大兄弟，这个问题比较严重，没有学过c#，那你只能慢慢来了 ╮(╯▽╰)╭

我是写nodejs的 现在想写个服务请求上级网关 解析报文的看了挺多 就没有组报文的吗。。 我用vscode 下了这个项目 不知道该怎么跑。。 启动调试选.net core 环境 然后就会弹一个launch.json出来

**Comment by SmallChi** [comment]
> 
> 
> > 大兄弟，这个问题比较严重，没有学过c#，那你只能慢慢来了 ╮(╯▽╰)╭
> 
> 我是写nodejs的 现在想写个服务请求上级网关 解析报文的看了挺多 就没有组报文的吗。。 我用vscode 下了这个项目 不知道该怎么跑。。 启动调试选.net core 环境 然后就会弹一个launch.json出来

有的，有的，在这个目录下面JT809.Protocol.Test找找看都是，demo的话就可以看[JT809.Protocol.Test\Simples](https://github.com/SmallChi/JT809/tree/master/src/JT809.Protocol.Test/Simples)

**Comment by KIngCrzy** [comment]
> > > 大兄弟，这个问题比较严重，没有学过c#，那你只能慢慢来了 ╮(╯▽╰)╭
> > 
> > 
> > 我是写nodejs的 现在想写个服务请求上级网关 解析报文的看了挺多 就没有组报文的吗。。 我用vscode 下了这个项目 不知道该怎么跑。。 启动调试选.net core 环境 然后就会弹一个launch.json出来
> 
> 有的，有的，在这个目录下面JT809.Protocol.Test找找看都是，demo的话就可以看[JT809.Protocol.Test\Simples](https://github.com/SmallChi/JT809/tree/master/src/JT809.Protocol.Test/Simples)

兄弟  上级平台发9005过来 我是回复9006吗 然后就可以发业务报文吗 怎么我发业务报文没返回了

**Comment by SmallChi** [comment]
猜测你没有认真拜读809的文档，文档前面有具体的流程，你应该要先熟悉清楚流程在开始搬砖。
