### ISSUE TITLE
车牌颜色代码有所增加

### ISSUE THREAD

**Issue by dev-Hanjing** [SmallChi/JT809#7]
首先感谢您分享这个库出来，解决了我的燃眉之急。但根据最新版本的交通运输行业标准《 JT/T 415-2021 道路运输电子政务平台信息分类与编码》中 6.4.11 车牌颜色代码的规定，您这个里面 JT809.Protocol.Enums.JT809VehicleColorType 中缺少对新能源车辆相关号牌颜色的定义。希望您能将新能源车的颜色定义加进去再发布一个新的版本在NuGet上。

_附：新版中颜色定义如下_
01    蓝色
02    黄色
03    黑色
04    白色
05    绿色
09    其它
91    农黄色
92    农绿色
93    黄绿色
94    渐变绿

**Comment by SmallChi** [comment]
好的，收到，今晚发布。

**Comment by dev-Hanjing** [comment]
感谢！！

**Comment by SmallChi** [comment]
@dev-Hanjing  跟net6一起发布预览版`Install-Package JT809 -Version 2.2.1-preview2`
