### ISSUE TITLE
解析的时候如何区分2011和2019版本

### ISSUE THREAD

**Issue by jixuan2012** [SmallChi/JT809#8]
解析的时候如何区分2011和2019版本

**Comment by yedajiang44** [comment]
由于2019版本809无法向下兼容，可以尝试以下方式

方法一

> 使用不同的端口区分

方法二

> 根据不同的接入码区分

方法三

> 借助消息头中的版本标志，自定义版本

当确定好报文是2011还是2019后，参考readme的[demo4](../#举个栗子4)，使用对应的版本进行反序列化

**Comment by jixuan2012** [comment]
明白了，多谢！
