### ISSUE TITLE
车载终端型号的长度好像是8字节的？

### ISSUE THREAD

**Issue by big-dream** [SmallChi/JT809#9]
https://github.com/SmallChi/JT809/blob/52db083c97fe613aad08bb731d4f5cbfd58caf60/src/JT809.Protocol/SubMessageBody/JT809_0x1200_0x1201.cs#L59-L61

2011 版本的车载终端型号的长度好像是 8 字节的，现在是20字节。

![image](https://github.com/SmallChi/JT809/assets/9215157/af5fdacc-1c8e-49f6-8355-f652fce32733)

**Comment by yedajiang44** [comment]
@big-dream 能否提供下报文？最好是在过检平台拿到的。谢谢~

**Comment by big-dream** [comment]
@yedajiang44 我也没有报文，只是在测试的时候，发现跟标准文档上定义的不一样。以下是自拟的测试报文
```hex
5b 00000067 00000001 1200 01020304 010203 00 00000000 d4c146383838383800000000000000000000000000 01 1201 00000031 ff00007fffffffffffffff 0102030405060708090a0b 0102030405060708  01020304050607 003133383030313338303030 74bf 5d
```

**Comment by yedajiang44** [comment]
不对不对！我突然想起来这是补充文档里有相关说明。

> 只有一个很久以前的一个截图

![image](https://github.com/SmallChi/JT809/assets/25813145/c96cfd44-95d5-4daf-861b-f9f0157d52fc)
